### PR TITLE
Build changes to support creating an OSGi bundle

### PR DESCRIPTION
**Pull request by dleblanc**
Creates an OSGi bundle with the BND tool.

I'm not familiar with your antlib approach, so I'll let you figure out how this should best live in there.

### CODE REVIEW

**Comment by dwdyer** [comment]
I'm ready to release a new version but I was wondering about the redundancy of having a separate OSGi bundle JAR in addition to the existing non-OSGi version.  Would it make more sense to have just one JAR, with the OSGi metadata included, to avoid confusion over which one the user should use?

I know almost nothing about OSGi - is the name of the JAR file significant, or could I just delete the original (non-OSGi) JAR file and re-name the one generated by the bnd task?  The result would then be that the release archive for the project includes only uncommons-maths-1.2.3.jar but that is the OSGi bundle.  Or is that not valid?

**Comment by dleblanc** [comment]
Hi Dan - yeah, all the OSGi stuff does is tag a little more metadata into
the manifest of the jar file. And the name of the jar file isn't
meaningful, so yeah, you could use the OSGi one in place of the other one
no problem (most projects do this).

Thanks Dan,

 -Dave

On Thu, Nov 22, 2012 at 8:59 AM, Dan Dyer notifications@github.com wrote:

> I'm ready to release a new version but I was wondering about the
> redundancy of having a separate OSGi bundle JAR in addition to the existing
> non-OSGi version. Would it make more sense to have just one JAR, with the
> OSGi metadata included, to avoid confusion over which one the user should
> use?
> 
> I know almost nothing about OSGi - is the name of the JAR file
> significant, or could I just delete the original (non-OSGi) JAR file and
> re-name the one generated by the bnd task? The result would then be that
> the release archive for the project includes only uncommons-maths-1.2.3.jar
> but that is the OSGi bundle. Or is that not valid?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dwdyer/uncommons-maths/pull/5#issuecomment-10640202.

## 

Dave LeBlanc david.leblanc@gmail.com

**Comment by dwdyer** [comment]
OK, thanks.  I've just released version 1.2.3 to the downloads section on GitHub.  If you are getting from Maven instead then you might need to track down whoever is responsible for uploading it to the appropriate repository.

**Comment by viktorklang** [comment]
Would you be able to publish it to Maven Central?

**Pull request merged**
